sudo: true
language: haskell
ghc:
  - "8.8.3"

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  Include:
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --system-ghc --test --no-run-tests --no-run-benchmarks

script:
  - stack test --system-ghc --fast

notifications:
  email: false
