name: "Cachix"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  cachix:
    name: ${{ matrix.os }} / Cachix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.3.4
      name: üì§ Checkout
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: cachix/install-nix-action@v13
      name: ‚ùÑÔ∏è  Set up Nix
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://hydra.iohk.io
          trusted-substituters = https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: cachix/cachix-action@v9
      name: üß∞ Cachix
      with:
        name: fission-2
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: üèóÔ∏è  Build
      run: nix-build -A fission-cli.components.exes.fission | cachix push fission-2
