name: Continuous Integration MacOS (no nix)

on:
  push: { "branches": [ "master" ] }
  pull_request: { "branches": [ "master" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: ðŸ“¥ Checkout repository
      uses: actions/checkout@v1

    - name: ðŸ§° Setup Stack
      uses: mstksg/setup-stack@v1

    - name: ðŸ”‘ Dependency Cache Key
      id: dep_cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml.lock | awk '{print $1}')

    - name: ðŸ’¾ Cache Dependencies
      id: cache_deps
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.dep_cache_key.outputs.key }}

    - name: ðŸ”‘ Artifact Cache Key
      id: art_cache_key
      run: echo ::set-output name=key::$(git branch)

    - name: ðŸ’¾ Cache Artifacts
      id: cache_arts
      uses: actions/cache@v1
      with:
        path: ./.stack-work/dist
        key: ${{ matrix.os }}-${{ steps.art_cache_key.outputs.key }}

    - name: Test
      run: |
        stack --no-terminal --no-nix test --fast
