name: Continuous Integration

on:
  push: { "branches": [ "master" ] }
  pull_request: { "branches": [ "master" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: ðŸ“¥ Checkout repository
      uses: actions/checkout@v1

    - name: ðŸ”‘ Dependency Cache Key
      id: dep_cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml.lock | awk '{print $1}')

    - name: ðŸ’¾ Cache Dependencies
      id: cache_deps
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.dep_cache_key.outputs.key }}

    - name: ðŸ”‘ Artifact Cache Key
      id: art_cache_key
      run: echo ::set-output name=key::$(git log --head | md5sum | awk '{print $1}')

    - name: ðŸ’¾ Cache Artifacts
      id: cache_arts
      uses: actions/cache@v1
      with:
        path: ./.stack-work/dist
        key: ${{ matrix.os }}-${{ steps.art_cache_key.outputs.key }}

    - name: ðŸ”¨ Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack build --fast

    - name: Test
      run: |
        stack --no-terminal test --fast
